services:
  # 1. The PostgreSQL Database
  db:
    image: postgres:15-alpine
    container_name: irctc_postgres
    environment:
      POSTGRES_DB: irctcdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: kb9gb11cr7  
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  # 2. The Redis Cache
  cache:
    image: redis:7-alpine
    container_name: irctc_redis
    ports:
      - "6379:6379"

  # 3. Your Spring Boot Application
  app:
    build: .
    container_name: irctc_backend
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy # Waits for Postgres to be fully ready
      cache:
        condition: service_started
    environment:
      # These environment variables overwrite your application.properties!
      # Notice we use the container names ('db' and 'cache') instead of 'localhost'
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/irctcdb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=kb9gb11cr7
      - SPRING_DATA_REDIS_HOST=cache
      - SPRING_DATA_REDIS_PORT=6379

volumes:
  postgres_data: