spring.application.name=irctc-clone
# 1. Run on port 8080
server.port=8080

# 2. Database Connection Settings
spring.datasource.url=jdbc:postgresql://localhost:5432/irctcdb
spring.datasource.username=postgres
spring.datasource.password=kb9gb11cr7

# 3. Hibernate Configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# Optional but helpful: Print the SQL queries in the terminal so we can see what Spring is doing
spring.jpa.show-sql=true