spring.application.name=irctc-clone
# 1. Run on port 8080
server.port=8080

# 2. Database Connection Settings
spring.datasource.url=jdbc:postgresql://localhost:5432/irctcdb
spring.datasource.username=postgres
spring.datasource.password=kb9gb11cr7

# 3. Hibernate Configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# Optional but helpful: Print the SQL queries in the terminal so we can see what Spring is doing
spring.jpa.show-sql=true

# Tell Spring Boot to strictly use Redis for caching
spring.cache.type=redis

# Point it to your Docker container
spring.data.redis.host=localhost
spring.data.redis.port=6379

# JWT Configuration (The Secret is a Base64 encoded 256-bit string)
jwt.secret=5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437
# Expiration time in milliseconds (86400000 ms = 24 hours)
jwt.expiration=86400000